services:

  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres:14.8-bookworm
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    command: postgres -p 5435
    expose:
      - 5435
  
  bot:
    container_name: bot
    restart: always
    image: roaddust2/outages-ge-bot:0.1.7
    env_file:
      - .env
    command: sh -c "alembic upgrade head && python3 -m app.main"
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres_volume: