"""Remove translated fields

Revision ID: 27374f23feaf
Revises: a3ead87ac4f4
Create Date: 2023-09-02 11:01:28.555109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27374f23feaf'
down_revision = 'a3ead87ac4f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_outages', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('sent_outages', sa.Column('info', sa.Text(), nullable=True))
    op.drop_constraint('chat_id_date_title_info_uc', 'sent_outages', type_='unique')
    op.create_unique_constraint('chat_id_date_title_info_uc', 'sent_outages', ['chat_id', 'date', 'title', 'info'])
    op.drop_column('sent_outages', 'geo_title')
    op.drop_column('sent_outages', 'en_info')
    op.drop_column('sent_outages', 'geo_info')
    op.drop_column('sent_outages', 'en_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_outages', sa.Column('en_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sent_outages', sa.Column('geo_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sent_outages', sa.Column('en_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sent_outages', sa.Column('geo_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('chat_id_date_title_info_uc', 'sent_outages', type_='unique')
    op.create_unique_constraint('chat_id_date_title_info_uc', 'sent_outages', ['chat_id', 'date', 'geo_title', 'geo_info'])
    op.drop_column('sent_outages', 'info')
    op.drop_column('sent_outages', 'title')
    # ### end Alembic commands ###
