"""Add full_address field to Address model

Revision ID: 504d572d3214
Revises: d4dddb7aabc9
Create Date: 2023-08-14 12:55:32.236551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504d572d3214'
down_revision = 'd4dddb7aabc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('full_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'full_address')
    # ### end Alembic commands ###
