"""Add timestamp field to SentOutage

Revision ID: 5c3b5217a283
Revises: da207b55b9c5
Create Date: 2023-09-08 11:20:11.395351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '5c3b5217a283'
down_revision = 'da207b55b9c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_outages', sa.Column('created_at', sa.DateTime(), nullable=True, server_default=func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sent_outages', 'created_at')
    # ### end Alembic commands ###
