"""add job_uuid field to Chat model

Revision ID: 6d440823786e
Revises: a3ead87ac4f4
Create Date: 2023-08-19 13:40:34.901014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d440823786e'
down_revision = 'a3ead87ac4f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('job_uuid', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'chats', ['job_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_column('chats', 'job_uuid')
    # ### end Alembic commands ###
