"""Update table 'outages' with emergency row

Revision ID: 7f755b058fde
Revises: c505df839654
Create Date: 2023-07-16 17:47:02.527172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f755b058fde'
down_revision = 'c505df839654'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outages', sa.Column('emergency', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outages', 'emergency')
    # ### end Alembic commands ###
