"""first migration

Revision ID: 9bb5bb32c40a
Revises: 
Create Date: 2023-07-24 20:17:16.234158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb5bb32c40a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('outages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('emergency', sa.Boolean(), nullable=False),
    sa.Column('geo_title', sa.String(length=255), nullable=True),
    sa.Column('en_title', sa.String(length=255), nullable=True),
    sa.Column('geo_info', sa.Text(), nullable=True),
    sa.Column('en_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'geo_title', 'geo_info', name='date_title_info_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outages')
    op.drop_table('chats')
    # ### end Alembic commands ###
