"""add unique constraint to SentOutage model

Revision ID: a3ead87ac4f4
Revises: 504d572d3214
Create Date: 2023-08-16 18:52:31.524373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ead87ac4f4'
down_revision = '504d572d3214'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('chat_id_date_title_info_uc', 'sent_outages', ['chat_id', 'date', 'geo_title', 'geo_info'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_id_date_title_info_uc', 'sent_outages', type_='unique')
    # ### end Alembic commands ###
