"""Create table 'outages'

Revision ID: c505df839654
Revises: 
Create Date: 2023-07-15 18:00:17.841365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c505df839654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('geo_title', sa.String(length=255), nullable=True),
    sa.Column('en_title', sa.String(length=255), nullable=True),
    sa.Column('geo_info', sa.Text(), nullable=True),
    sa.Column('en_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outages')
    # ### end Alembic commands ###
