"""Add unique constraint to Address model

Revision ID: d4dddb7aabc9
Revises: aafa4dc55c83
Create Date: 2023-08-12 12:30:05.465730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dddb7aabc9'
down_revision = 'aafa4dc55c83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('chat_id_city_street_uc', 'addresses', ['chat_id', 'city', 'street'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_id_city_street_uc', 'addresses', type_='unique')
    # ### end Alembic commands ###
