name: Deploy

on:
  push:
    branches:
      - main

jobs:
  lint_test:
    name: Lint & Test
    uses: ./.github/workflows/lint_test.yml
    secrets: inherit
  code_coverage:
    name: Code coverage
    uses: ./.github/workflows/code_coverage.yml
    needs: [lint_test]
    secrets: inherit
