name: Lint & Test

on:
  workflow_call:

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run linter
        run: |
          make lint
      - name: Run pytest
        run: |
          make test
